"""adicionar itens no Pedido

Revision ID: 58a918cb646b
Revises: 8983a1d21f65
Create Date: 2025-12-17 06:09:43.640107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a918cb646b'
down_revision: Union[str, Sequence[str], None] = '8983a1d21f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedidos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_pedidos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=True),
    sa.Column('sabor', sa.VARCHAR(), nullable=True),
    sa.Column('tamanho', sa.VARCHAR(), nullable=True),
    sa.Column('preco_unitario', sa.FLOAT(), nullable=True),
    sa.Column('pedido', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pedido'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
